
---
- name: Prerequisite for k8s cluster deployment
  hosts: worker
  become: yes

  tasks:
    - name: Configure timezone
      ansible.builtin.shell:
        cmd: timedatectl set-timezone Asia/Kuala_Lumpur

    - name: Update and upgrade OS patch
      ansible.builtin.apt:
        update_cache: true
        upgrade: full

    - name: Disable apparmor
      ansible.builtin.apt:
        name: apparmor
        state: absent

    - name: Disable swap
      ansible.builtin.command: swapoff -a
      ignore_errors: yes

    - name: Remove swap entry from /etc/fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        state: absent
        regexp: '/swap.img'
        insertafter: '#/swap.img*'

    - name: Remove swapfile
      ansible.builtin.file :
        path: /swapfile
        state: absent
