- name: Add Zabbix repository
  ansible.builtin.yum:
    name: https://repo.zabbix.com/zabbix/7.2/rhel/9/x86_64/zabbix-release-7.2-1.el9.noarch.rpm
    state: present

- name: Install Zabbix Agent 2
  ansible.builtin.yum:
    name: zabbix-agent2
    state: present

- name: Configure Zabbix Agent 2
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Server='
    line: 'Server=127.0.0.1'  # Replace with your Zabbix server IP or hostname
    state: present
  notify: Restart Zabbix Agent 2

- name: Enable and start Zabbix Agent 2 service
  ansible.builtin.service:
    name: zabbix-agent2
    enabled: yes
    state: started

# Handlers to restart the service when configuration changes
handlers:
  - name: Restart Zabbix Agent 2
    ansible.builtin.service:
      name: zabbix-agent2
      state: restarted
