- name: Stop Zabbix agent service
  ansible.builtin.service:
    name: zabbix-agent2
    state: stopped
    enabled: no

- name: Remove Zabbix agent package
  ansible.builtin.apt:
    name: zabbix-agent2
    state: absent
    purge: yes

- name: Remove Zabbix configuration files
  ansible.builtin.file:
    path: /etc/zabbix
    state: absent

- name: Remove Zabbix log files
  ansible.builtin.file:
    path: /var/log/zabbix
    state: absent

- name: Remove Zabbix user and group
  ansible.builtin.user:
    name: zabbix
    state: absent
    remove: yes
